#!/bin/sh
#
# jmxsh
#
# A shell wrapper for jmxsh.
#
# Assumes java is in the PATH.  If not, will need to edit this script.
#
# You'll need to modify this when you find a place to jmxsh.
#
for i in . /usr/lib
do
  if [ -f $i/jmxsh.jar ]; then
    JMXSH_JARFILE=$i/jmxsh.jar
    break;
  fi
done

if [ -z "JMXSH_JARFILE" ]; then
  echo "ERROR: Cannot find jmxsh.jar."
  exit 1
fi

if [ -n "$JAVA_HOME" ]; then
  JAVA=$JAVA_HOME/bin/java
else
  JAVA=java
fi

exec $JAVA -jar $JMXSH_JARFILE "$@"
